### PR TITLE
Generate classes more pythonically

### PR DESCRIPTION
**Pull request by PaulWay**
It's fairly standard in Python to have the __init__ method initialise the
object from given data, rather than using a separate class method as an
initialiser.  This work moves the 'dictToObject' code into the class
initialiser.

We also do a couple of simplifications:

* It's preferable not to use 'dict' as a variable name, even if it is
  actually a dictionary variable and even if Python understands that
  you're using a keyword as a variable.  So we rename this to 'config'.
* Using list comprehensions allows Python to pre-allocate the list to a
  given size, rather than appending items having to extend the list each
  iteration.
* The iterating variable doesn't have to be uniquely named, nor do we
  need a separate variable to take the data from the config that's
  then going to be iterated through.

I may be missing some reason why we used the 'dictToObject' class method
instead of standard initialisation, so please let me know if that makes
more sense.

Signed-off-by: Paul Wayper <paulway@redhat.com>

### CODE REVIEW

**Comment by OkieOth** [comment]
Hi Paul, thank you for the contribution and sorry for the late response. I am going to check the changes later this evening

**Comment by OkieOth** [comment]
Hi Paul, I checked your changes and I can't use your pythonBeans.mako to the generate the yacg code (`bin/generateCodeForYacg.sh`) ... got some syntax errors. Nevertheless your recommendations are reasonable and I always try to improve :-}

**Comment by PaulWay** [comment]
Hi there!  OK, were there tests that were failing?  Should we put some tests in so that we can pick up the syntax errors?

**Comment by PaulWay** [comment]
I've fixed the syntax error (didn't need the ${} around `pythonFuncs.getDefaultPythonValue(property)` in line 82), but now I'm getting errors running that `generateCodeForYacg.sh` script.  And it doesn't seem to be based on the code being generated in `pythonBeans.mako`.  So I'm figuring that out now.

**Comment by PaulWay** [comment]
Yeah, I don't understand how the `yacg/model/model.py` gets generated.  I've updated the `pythonBeans.mako` template but the `yacg/model/model.py` file isn't being regenerated from that.  Maybe I need to run the tests again?

**Comment by PaulWay** [comment]
Interesting - just worked out that if the `yacg/model/model.py` file doesn't work, you can't use yacg to regenerate it.  Thank Shiznax for `git checkout` :-)

**Comment by OkieOth** [comment]
Yep, in someway strange :D. I am using to codegen to create parts of this application to. But I am no Python expert. I picked the language only fot its nice template engines - I know weak excuse for the issue with the model.py ;-)
In every generation task for the yacg code the generated classes are reloaded. That makes debugging with that code a bit cumbersome, but since I usually generate code for other projects, this behaviour isn't a real problem

**Comment by OkieOth** [comment]
I reviewed what you did in your code and decided to go further with a separate function to init from dictionaries, but as you proposed is it now called from the __init__ function. I decided to let it in a separate function to keep the init function smaller and more readable. I also renamed the 'dict' var to 'dictObj' - since 'config' is here misleading. It is used in this code to build the objects from the config files, but I used it somewhere also in another context.

**Comment by OkieOth** [comment]
What's your opinion about this version?
[improved version in branch 'improve_pythonBeans_template'](https://github.com/OkieOth/yacg/blob/improve_pythonBeans_template/yacg/generators/templates/pythonBeans.mako
)

**Comment by OkieOth** [comment]
Tests are running, but some additional tests for the github actions still cause errors. I am going to look at this tomorrow or in the next days.

**Comment by PaulWay** [comment]
I arrived at the `__init__(self, config=dict())` solution, which is similar to your `__init__(self, dictObj=None)` solution.  I think the `None` detection is better, and it kind of makes your line `if dictObj is not None:` redundant in line 82 (as that's about to be done by line 86).

**Comment by PaulWay** [comment]
I'm just not convinced that the Python object needs to separate the `__init__` and the `initFromDict` methods.

**Comment by OkieOth** [comment]
It's not separated ... it is called in the __init__ ... only for clean code reasons ;-)

**Comment by OkieOth** [comment]
@PaulWay I implemented your recommendation in that way:
https://github.com/OkieOth/yacg/blob/master/yacg/model/model.py#L298

I hope you like it more :D 
Since I wasn't able to merge your PR your contribution is hidden. As compensation I mentioned you in the changelog.

Thank you and have a nice day.
BR, Eiko

**Pull request merged**
